name: gsc
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    sqflite: ^2.3.3
    sqflite_common_ffi: ^2.3.3
    path: ^1.9.0
    path_provider: ^2.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/poem.db
