name: gsc
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    adaptive_theme: ^3.6.0
    cupertino_icons: ^1.0.6
    dropdown_button2: ^3.0.0-beta.12
    flutter_html: ^3.0.0-beta.2
    flutter_modular: ^6.3.2
    flutter_smart_dialog: ^4.9.4
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.1.2
    sqflite: ^2.3.3
    sqflite_common_ffi: ^2.3.3
    window_manager: ^0.3.8
    provider: ^6.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/poem.db
        - assets/images/
